---
# tasks file for cloudera-vm

- name: Cloudera Manager
  include_role:
    name: cloudera

- name: Init DB and DBFeeder
  include_tasks: init_db.yml

- name: Change root password
  user:
    name: root
    password: "{{ root_passwd }}"
