---

- name: Create Real Time ETL dir
  file:
    path: /opt/devops/realtime_etl
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Create Batch ML dir
  file:
    path: /opt/devops/batch_ml
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Create Real Time ML dir
  file:
    path: /opt/devops/realtime_ml
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Create Batch ETL  dir
  file:
    path: /opt/devops/batch_etl
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Create default folders
  include_role:
    name: devops-folders
