---
# tasks file for devops-worker

- name: Install SBT
  include_role:
    name: sbt
    
- name: Install Spark
  include_role:
    name: spark

- name: Install Confluent
  include_role:
    name: confluent

- name: Setup Kafka JDBC Source connector
  include_role:
    name: kafka-jdbc-connector

- name: Set hive-site.xml
  copy:
    src: hive-site.xml
    dest: $SPARK_HOME/conf/hive-site.xml
    owner: root
    group: root
    mode: 0644
  become: true
  become_flags: '-i'

- name: setup folders
  include_tasks: folders.yml
