---
# tasks file for ansible

- name: Install python devl
  yum:
    name: python-devel
    state: latest

- name: Install python pip
  yum:
    name: python-pip
    state: latest

- name: Install git
  yum:
    name: git
    state: latest

- name: Install ansible
  pip:
    name: ansible


