
- hosts: all
  #hosts: worker
  #connection: local
  become: yes
  become_user: root
  tasks:

    - name: Ensure Real Time ML service is down
      service:
        name: devops-rtml
        state: stopped
      
    - name: Deploy Real time ml webapp
      copy:
        src: /opt/deploy/realtime_ml/
        dest: /opt/devops/realtime_ml/
        owner: root
        group: root
        mode: 0777
        force: yes

    - name: Ensure Real Time ML service is running and start on boot
      service:
        name: devops-rtml
        state: started
        #enabled: yes
