
- hosts: all
  #hosts: worker
  #connection: local
  become: yes
  become_user: root
  tasks:
    - name: Ensure Real Time ETL services are down
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - devops-rtetl-ratings
        - devops-rtetl-tags

    - name: Deploy Real Time ETL in Production
      copy:
        src: /opt/deploy/realtime_etl/
        dest: /opt/devops/realtime_etl/
        owner: root
        group: root
        mode: 0777
        force: yes

    - name: Ensure Kafka JDBC connector is running
      service:
        name: devops-kafka-jdbc-connector
        state: started


    - name: Ensure Real Time ETL services are running and start on boot
      service:
        name: "{{ item }}"
        state: started
        #enabled: yes
      with_items:
        - devops-rtetl-ratings
        - devops-rtrtl-tags
