---
# tasks file for ci-server

- name: Install sbt
  include_role:
    name: sbt

- name: Install spark
  include_role:
    name: spark

- name: Install Jenkins Blue Ocean
  include_role:
    name: jenkins
