---
# tasks file for init_db.yml

- name: Setup DBFeeder and movielens dataset
  include_role:
    name: movielens-init

- name: Read generated cloudera-scm password
  shell: head -1 /var/lib/cloudera-scm-server-db/data/generated_password.txt
  register: password

- debug:
    msg: "{{ password['stdout'] }}"

- name: Schedule DBFeeder daily
  cron:
    name: "Ingest movielens"
    user: root
    special_time: daily
    job: python $DBFEEDER_HOME/DBFeeder.py --fraction=0.001 --datasets=$M20_PATH --psql_user=cloudera-scm --psql_password="{{ password['stdout'] }}"
  register: first_run

- name: initialize database
  command: sudo -i python $DBFEEDER_HOME/DBFeeder.py --init --datasets=$M20_PATH --psql_user=cloudera-scm --psql_password="{{ password['stdout'] }}"
  when: first_run.changed
  
