
- hosts: all
  #hosts: worker
  connection: local
  become: yes
  become_user: root
  roles:
    - devops-worker
    - ci-server
    - orchestrator
    - prometheus
    - prometheus-node-exporter
    - prometheus-pushgateway
